# Generated by Django 4.2.9 on 2024-02-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_profile_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountUser',
        ),
    ]
